/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 401efa3e1d050252c4d3c477b44428a0)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
    durableNamespaces: 'UserSession' | 'ProjectDoc';
  }
  interface ProductionEnv {
    PDF_BUCKET: R2Bucket;
    DB: D1Database;
    EMAIL_QUEUE: Queue;
    ASSETS: Fetcher;
    ENVIRONMENT: 'production';
    APP_URL: 'https://corates.org';
    AUTH_BASE_URL: 'https://corates.org';
    VITE_API_URL: string;
    VITE_PUBLIC_APP_URL: string;
    VITE_BASEPATH: string;
    VITE_GOOGLE_PICKER_API_KEY: string;
    VITE_GOOGLE_PICKER_APP_ID: string;
    VITE_DEV_PANEL: string;
    VITE_SENTRY_DSN: string;
    USER_SESSION: DurableObjectNamespace<import('./src/server').UserSession>;
    PROJECT_DOC: DurableObjectNamespace<import('./src/server').ProjectDoc>;
  }
  interface Env {
    PDF_BUCKET: R2Bucket;
    DB: D1Database;
    EMAIL_QUEUE: Queue;
    ASSETS: Fetcher;
    ENVIRONMENT: 'production' | 'development';
    APP_URL: 'https://corates.org' | 'http://localhost:3010';
    AUTH_BASE_URL: 'https://corates.org' | 'http://localhost:8787';
    VITE_API_URL: string;
    VITE_PUBLIC_APP_URL: string;
    VITE_BASEPATH: string;
    VITE_GOOGLE_PICKER_API_KEY: string;
    VITE_GOOGLE_PICKER_APP_ID: string;
    VITE_DEV_PANEL: string;
    VITE_SENTRY_DSN: string;
    USER_SESSION: DurableObjectNamespace<import('./src/server').UserSession>;
    PROJECT_DOC: DurableObjectNamespace<import('./src/server').ProjectDoc>;
    DEV_MODE?: true;
    SENTRY_DSN?: 'https://3ddf61abb06680bffc1ebc7f540f05de@o4510738063818752.ingest.us.sentry.io/4510738126274560';
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ENVIRONMENT'
      | 'APP_URL'
      | 'AUTH_BASE_URL'
      | 'VITE_API_URL'
      | 'VITE_PUBLIC_APP_URL'
      | 'VITE_BASEPATH'
      | 'VITE_GOOGLE_PICKER_API_KEY'
      | 'VITE_GOOGLE_PICKER_APP_ID'
      | 'VITE_DEV_PANEL'
      | 'VITE_SENTRY_DSN'
      | 'DEV_MODE'
      | 'SENTRY_DSN'
    >
  > {}
}
