/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e0611d0ad8116ec93967a3ff3824d864)
interface __BaseEnv_Env {
  PDF_BUCKET: R2Bucket;
  DB: D1Database;
  EMAIL_QUEUE: Queue;
  CF_VERSION_METADATA: WorkerVersionMetadata;
  ASSETS: Fetcher;
  ENVIRONMENT: 'production' | 'staging' | 'development';
  DEV_MODE: false | true;
  APP_URL: 'https://corates.org' | 'https://staging.corates.org' | 'https://corates.localhost';
  AUTH_BASE_URL:
    'https://corates.org' | 'https://staging.corates.org' | 'https://corates.localhost';
  SENTRY_DSN?: 'https://3ddf61abb06680bffc1ebc7f540f05de@o4510738063818752.ingest.us.sentry.io/4510738126274560';
  VITE_API_URL: string;
  VITE_PUBLIC_APP_URL: string;
  VITE_BASEPATH: string;
  VITE_GOOGLE_PICKER_API_KEY: string;
  VITE_GOOGLE_PICKER_APP_ID: string;
  VITE_DEV_PANEL: string;
  VITE_SENTRY_DSN: string;
  CLOUDFLARE_API_TOKEN: string;
  AUTH_SECRET: string;
  STRUCTURED_LOGS: string;
  EMAIL_FROM: string;
  POSTMARK_SERVER_TOKEN: string;
  SEND_EMAILS_IN_DEV: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  ORCID_CLIENT_ID: string;
  ORCID_CLIENT_SECRET: string;
  ADMIN_EMAIL: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET_AUTH: string;
  STRIPE_WEBHOOK_SECRET_PURCHASES: string;
  STRIPE_PRICE_ID_TEAM_MONTHLY: string;
  STRIPE_PRICE_ID_TEAM_YEARLY: string;
  STRIPE_PRICE_ID_LAB_MONTHLY: string;
  STRIPE_PRICE_ID_LAB_YEARLY: string;
  STRIPE_AI_AGENT_KEY: string;
  USER_SESSION: DurableObjectNamespace<import('./src/server').UserSession>;
  PROJECT_DOC: DurableObjectNamespace<import('./src/server').ProjectDoc>;
  WORKSPACE: DurableObjectNamespace<import('./src/server').WorkspaceDO>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/server');
    durableNamespaces: 'UserSession' | 'ProjectDoc' | 'WorkspaceDO';
  }
  interface ProductionEnv {
    PDF_BUCKET: R2Bucket;
    DB: D1Database;
    EMAIL_QUEUE: Queue;
    CF_VERSION_METADATA: WorkerVersionMetadata;
    ASSETS: Fetcher;
    ENVIRONMENT: 'production';
    DEV_MODE: false;
    APP_URL: 'https://corates.org';
    AUTH_BASE_URL: 'https://corates.org';
    SENTRY_DSN: 'https://3ddf61abb06680bffc1ebc7f540f05de@o4510738063818752.ingest.us.sentry.io/4510738126274560';
    VITE_API_URL: string;
    VITE_PUBLIC_APP_URL: string;
    VITE_BASEPATH: string;
    VITE_GOOGLE_PICKER_API_KEY: string;
    VITE_GOOGLE_PICKER_APP_ID: string;
    VITE_DEV_PANEL: string;
    VITE_SENTRY_DSN: string;
    CLOUDFLARE_API_TOKEN: string;
    AUTH_SECRET: string;
    STRUCTURED_LOGS: string;
    EMAIL_FROM: string;
    POSTMARK_SERVER_TOKEN: string;
    SEND_EMAILS_IN_DEV: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    ORCID_CLIENT_ID: string;
    ORCID_CLIENT_SECRET: string;
    ADMIN_EMAIL: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET_AUTH: string;
    STRIPE_WEBHOOK_SECRET_PURCHASES: string;
    STRIPE_PRICE_ID_TEAM_MONTHLY: string;
    STRIPE_PRICE_ID_TEAM_YEARLY: string;
    STRIPE_PRICE_ID_LAB_MONTHLY: string;
    STRIPE_PRICE_ID_LAB_YEARLY: string;
    STRIPE_AI_AGENT_KEY: string;
    USER_SESSION: DurableObjectNamespace<import('./src/server').UserSession>;
    PROJECT_DOC: DurableObjectNamespace<import('./src/server').ProjectDoc>;
    WORKSPACE: DurableObjectNamespace<import('./src/server').WorkspaceDO>;
  }
  interface StagingEnv {
    PDF_BUCKET: R2Bucket;
    DB: D1Database;
    EMAIL_QUEUE: Queue;
    CF_VERSION_METADATA: WorkerVersionMetadata;
    ASSETS: Fetcher;
    ENVIRONMENT: 'staging';
    DEV_MODE: true;
    APP_URL: 'https://staging.corates.org';
    AUTH_BASE_URL: 'https://staging.corates.org';
    VITE_API_URL: string;
    VITE_PUBLIC_APP_URL: string;
    VITE_BASEPATH: string;
    VITE_GOOGLE_PICKER_API_KEY: string;
    VITE_GOOGLE_PICKER_APP_ID: string;
    VITE_DEV_PANEL: string;
    VITE_SENTRY_DSN: string;
    CLOUDFLARE_API_TOKEN: string;
    AUTH_SECRET: string;
    STRUCTURED_LOGS: string;
    EMAIL_FROM: string;
    POSTMARK_SERVER_TOKEN: string;
    SEND_EMAILS_IN_DEV: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    ORCID_CLIENT_ID: string;
    ORCID_CLIENT_SECRET: string;
    ADMIN_EMAIL: string;
    STRIPE_SECRET_KEY: string;
    STRIPE_WEBHOOK_SECRET_AUTH: string;
    STRIPE_WEBHOOK_SECRET_PURCHASES: string;
    STRIPE_PRICE_ID_TEAM_MONTHLY: string;
    STRIPE_PRICE_ID_TEAM_YEARLY: string;
    STRIPE_PRICE_ID_LAB_MONTHLY: string;
    STRIPE_PRICE_ID_LAB_YEARLY: string;
    STRIPE_AI_AGENT_KEY: string;
    USER_SESSION: DurableObjectNamespace<import('./src/server').UserSession>;
    PROJECT_DOC: DurableObjectNamespace<import('./src/server').ProjectDoc>;
    WORKSPACE: DurableObjectNamespace<import('./src/server').WorkspaceDO>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'ENVIRONMENT'
      | 'DEV_MODE'
      | 'APP_URL'
      | 'AUTH_BASE_URL'
      | 'SENTRY_DSN'
      | 'VITE_API_URL'
      | 'VITE_PUBLIC_APP_URL'
      | 'VITE_BASEPATH'
      | 'VITE_GOOGLE_PICKER_API_KEY'
      | 'VITE_GOOGLE_PICKER_APP_ID'
      | 'VITE_DEV_PANEL'
      | 'VITE_SENTRY_DSN'
      | 'CLOUDFLARE_API_TOKEN'
      | 'AUTH_SECRET'
      | 'STRUCTURED_LOGS'
      | 'EMAIL_FROM'
      | 'POSTMARK_SERVER_TOKEN'
      | 'SEND_EMAILS_IN_DEV'
      | 'GOOGLE_CLIENT_ID'
      | 'GOOGLE_CLIENT_SECRET'
      | 'ORCID_CLIENT_ID'
      | 'ORCID_CLIENT_SECRET'
      | 'ADMIN_EMAIL'
      | 'STRIPE_SECRET_KEY'
      | 'STRIPE_WEBHOOK_SECRET_AUTH'
      | 'STRIPE_WEBHOOK_SECRET_PURCHASES'
      | 'STRIPE_PRICE_ID_TEAM_MONTHLY'
      | 'STRIPE_PRICE_ID_TEAM_YEARLY'
      | 'STRIPE_PRICE_ID_LAB_MONTHLY'
      | 'STRIPE_PRICE_ID_LAB_YEARLY'
      | 'STRIPE_AI_AGENT_KEY'
    >
  > {}
}
