/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppProtectedRouteImport } from './routes/_app/_protected'
import { Route as AppChecklistRouteImport } from './routes/_app/checklist'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AuthCompleteProfileRouteImport } from './routes/_auth/complete-profile'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as ApiClientLogsRouteImport } from './routes/api/client-logs'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesAmstar2RouteImport } from './routes/resources/amstar2'
import { Route as ResourcesAmstar2VsRobisRouteImport } from './routes/resources/amstar2-vs-robis'
import { Route as ResourcesRob1VsRob2RouteImport } from './routes/resources/rob1-vs-rob2'
import { Route as ResourcesRob2RouteImport } from './routes/resources/rob2'
import { Route as ResourcesRob2VsRobinsIRouteImport } from './routes/resources/rob2-vs-robins-i'
import { Route as ResourcesRobinsIRouteImport } from './routes/resources/robins-i'
import { Route as ResourcesRobinsIV1VsV2RouteImport } from './routes/resources/robins-i-v1-vs-v2'
import { Route as SecurityDisclosureRouteImport } from './routes/security_.disclosure'
import { Route as AppProtectedWorkspaceRouteImport } from './routes/_app/_protected/$workspace'
import { Route as AppProtectedAdminRouteImport } from './routes/_app/_protected/admin'
import { Route as AppProtectedSettingsRouteImport } from './routes/_app/_protected/settings'
import { Route as AppChecklistIndexRouteImport } from './routes/_app/checklist.index'
import { Route as AppChecklistChecklistIdRouteImport } from './routes/_app/checklist.$checklistId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthVerifyEmailRouteImport } from './routes/api/auth/verify-email'
import { Route as ApiTestAddProjectMemberRouteImport } from './routes/api/test/add-project-member'
import { Route as ApiTestAuthCodeRouteImport } from './routes/api/test/auth-code'
import { Route as ApiTestAuthUrlRouteImport } from './routes/api/test/auth-url'
import { Route as ApiTestCleanupRouteImport } from './routes/api/test/cleanup'
import { Route as ApiTestCleanupUserByEmailRouteImport } from './routes/api/test/cleanup-user-by-email'
import { Route as ApiTestHealthRouteImport } from './routes/api/test/health'
import { Route as ApiTestResetRouteImport } from './routes/api/test/reset'
import { Route as ApiTestSeedRouteImport } from './routes/api/test/seed'
import { Route as ApiTestSessionRouteImport } from './routes/api/test/session'
import { Route as ApiTestUpdateSubscriptionRouteImport } from './routes/api/test/update-subscription'
import { Route as ApiTestVerifyEmailRouteImport } from './routes/api/test/verify-email'
import { Route as ApiUsersAvatarRouteImport } from './routes/api/users/avatar'
import { Route as AppProtectedWorkspaceIndexRouteImport } from './routes/_app/_protected/$workspace/index'
import { Route as AppProtectedWorkspaceSettingsRouteImport } from './routes/_app/_protected/$workspace/settings'
import { Route as AppProtectedAdminIndexRouteImport } from './routes/_app/_protected/admin/index'
import { Route as AppProtectedAdminAnnouncementsRouteImport } from './routes/_app/_protected/admin/announcements'
import { Route as AppProtectedAdminDatabaseRouteImport } from './routes/_app/_protected/admin/database'
import { Route as AppProtectedAdminStorageRouteImport } from './routes/_app/_protected/admin/storage'
import { Route as AppProtectedOrgsNewRouteImport } from './routes/_app/_protected/orgs.new'
import { Route as AppProtectedProjectsSplatRouteImport } from './routes/_app/_protected/projects.$'
import { Route as AppProtectedSettingsIndexRouteImport } from './routes/_app/_protected/settings/index'
import { Route as AppProtectedSettingsSplatRouteImport } from './routes/_app/_protected/settings/$'
import { Route as ApiAuthStripeWebhookRouteImport } from './routes/api/auth/stripe/webhook'
import { Route as ApiUsersAvatarUserIdRouteImport } from './routes/api/users/avatar/$userId'
import { Route as AppProtectedWorkspaceProjectsProjectIdRouteImport } from './routes/_app/_protected/$workspace/projects.$projectId'
import { Route as AppProtectedWorkspaceSettingsIndexRouteImport } from './routes/_app/_protected/$workspace/settings/index'
import { Route as AppProtectedWorkspaceSettingsBillingRouteImport } from './routes/_app/_protected/$workspace/settings/billing'
import { Route as AppProtectedWorkspaceSettingsPlansRouteImport } from './routes/_app/_protected/$workspace/settings/plans'
import { Route as AppProtectedAdminBillingLedgerRouteImport } from './routes/_app/_protected/admin/billing.ledger'
import { Route as AppProtectedAdminBillingStripeToolsRouteImport } from './routes/_app/_protected/admin/billing.stripe-tools'
import { Route as AppProtectedAdminBillingStuckStatesRouteImport } from './routes/_app/_protected/admin/billing.stuck-states'
import { Route as AppProtectedAdminOrgsIndexRouteImport } from './routes/_app/_protected/admin/orgs.index'
import { Route as AppProtectedAdminOrgsOrgIdRouteImport } from './routes/_app/_protected/admin/orgs.$orgId'
import { Route as AppProtectedAdminProjectsIndexRouteImport } from './routes/_app/_protected/admin/projects.index'
import { Route as AppProtectedAdminProjectsProjectIdRouteImport } from './routes/_app/_protected/admin/projects.$projectId'
import { Route as AppProtectedAdminUsersIndexRouteImport } from './routes/_app/_protected/admin/users.index'
import { Route as AppProtectedAdminUsersUserIdRouteImport } from './routes/_app/_protected/admin/users.$userId'
import { Route as AppProtectedSettingsAccountIntegrationsRouteImport } from './routes/_app/_protected/settings/account/integrations'
import { Route as AppProtectedSettingsAccountPreferencesRouteImport } from './routes/_app/_protected/settings/account/preferences'
import { Route as AppProtectedSettingsAccountProfileRouteImport } from './routes/_app/_protected/settings/account/profile'
import { Route as AppProtectedSettingsAccountSecurityRouteImport } from './routes/_app/_protected/settings/account/security'
import { Route as ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteImport } from './routes/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
import { Route as AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport } from './routes/_app/_protected/$workspace/projects.$projectId/studies.$studyId.checklists.$checklistId'
import { Route as ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRouteImport } from './routes/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
import { Route as AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport } from './routes/_app/_protected/$workspace/projects.$projectId/studies.$studyId.reconcile.$checklist1Id.$checklist2Id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientLogsRoute = ApiClientLogsRouteImport.update({
  id: '/api/client-logs',
  path: '/api/client-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAmstar2Route = ResourcesAmstar2RouteImport.update({
  id: '/resources/amstar2',
  path: '/resources/amstar2',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAmstar2VsRobisRoute = ResourcesAmstar2VsRobisRouteImport.update({
  id: '/resources/amstar2-vs-robis',
  path: '/resources/amstar2-vs-robis',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRob1VsRob2Route = ResourcesRob1VsRob2RouteImport.update({
  id: '/resources/rob1-vs-rob2',
  path: '/resources/rob1-vs-rob2',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRob2Route = ResourcesRob2RouteImport.update({
  id: '/resources/rob2',
  path: '/resources/rob2',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRob2VsRobinsIRoute = ResourcesRob2VsRobinsIRouteImport.update({
  id: '/resources/rob2-vs-robins-i',
  path: '/resources/rob2-vs-robins-i',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRobinsIRoute = ResourcesRobinsIRouteImport.update({
  id: '/resources/robins-i',
  path: '/resources/robins-i',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRobinsIV1VsV2Route = ResourcesRobinsIV1VsV2RouteImport.update({
  id: '/resources/robins-i-v1-vs-v2',
  path: '/resources/robins-i-v1-vs-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityDisclosureRoute = SecurityDisclosureRouteImport.update({
  id: '/security_/disclosure',
  path: '/security/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedWorkspaceRoute = AppProtectedWorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedAdminRoute = AppProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedSettingsRoute = AppProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppChecklistIndexRoute = AppChecklistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppChecklistRoute,
} as any)
const AppChecklistChecklistIdRoute = AppChecklistChecklistIdRouteImport.update({
  id: '/$checklistId',
  path: '/$checklistId',
  getParentRoute: () => AppChecklistRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyEmailRoute = ApiAuthVerifyEmailRouteImport.update({
  id: '/api/auth/verify-email',
  path: '/api/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAddProjectMemberRoute = ApiTestAddProjectMemberRouteImport.update({
  id: '/api/test/add-project-member',
  path: '/api/test/add-project-member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAuthCodeRoute = ApiTestAuthCodeRouteImport.update({
  id: '/api/test/auth-code',
  path: '/api/test/auth-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAuthUrlRoute = ApiTestAuthUrlRouteImport.update({
  id: '/api/test/auth-url',
  path: '/api/test/auth-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCleanupRoute = ApiTestCleanupRouteImport.update({
  id: '/api/test/cleanup',
  path: '/api/test/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestCleanupUserByEmailRoute =
  ApiTestCleanupUserByEmailRouteImport.update({
    id: '/api/test/cleanup-user-by-email',
    path: '/api/test/cleanup-user-by-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTestHealthRoute = ApiTestHealthRouteImport.update({
  id: '/api/test/health',
  path: '/api/test/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestResetRoute = ApiTestResetRouteImport.update({
  id: '/api/test/reset',
  path: '/api/test/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSeedRoute = ApiTestSeedRouteImport.update({
  id: '/api/test/seed',
  path: '/api/test/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSessionRoute = ApiTestSessionRouteImport.update({
  id: '/api/test/session',
  path: '/api/test/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestUpdateSubscriptionRoute =
  ApiTestUpdateSubscriptionRouteImport.update({
    id: '/api/test/update-subscription',
    path: '/api/test/update-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTestVerifyEmailRoute = ApiTestVerifyEmailRouteImport.update({
  id: '/api/test/verify-email',
  path: '/api/test/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersAvatarRoute = ApiUsersAvatarRouteImport.update({
  id: '/api/users/avatar',
  path: '/api/users/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProtectedWorkspaceIndexRoute =
  AppProtectedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedWorkspaceRoute,
  } as any)
const AppProtectedWorkspaceSettingsRoute =
  AppProtectedWorkspaceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProtectedWorkspaceRoute,
  } as any)
const AppProtectedAdminIndexRoute = AppProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProtectedAdminRoute,
} as any)
const AppProtectedAdminAnnouncementsRoute =
  AppProtectedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminDatabaseRoute =
  AppProtectedAdminDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminStorageRoute =
  AppProtectedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedOrgsNewRoute = AppProtectedOrgsNewRouteImport.update({
  id: '/orgs/new',
  path: '/orgs/new',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedProjectsSplatRoute =
  AppProtectedProjectsSplatRouteImport.update({
    id: '/projects/$',
    path: '/projects/$',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedSettingsIndexRoute =
  AppProtectedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const AppProtectedSettingsSplatRoute =
  AppProtectedSettingsSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const ApiAuthStripeWebhookRoute = ApiAuthStripeWebhookRouteImport.update({
  id: '/api/auth/stripe/webhook',
  path: '/api/auth/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersAvatarUserIdRoute = ApiUsersAvatarUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersAvatarRoute,
} as any)
const AppProtectedWorkspaceProjectsProjectIdRoute =
  AppProtectedWorkspaceProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppProtectedWorkspaceRoute,
  } as any)
const AppProtectedWorkspaceSettingsIndexRoute =
  AppProtectedWorkspaceSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedWorkspaceSettingsRoute,
  } as any)
const AppProtectedWorkspaceSettingsBillingRoute =
  AppProtectedWorkspaceSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppProtectedWorkspaceSettingsRoute,
  } as any)
const AppProtectedWorkspaceSettingsPlansRoute =
  AppProtectedWorkspaceSettingsPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AppProtectedWorkspaceSettingsRoute,
  } as any)
const AppProtectedAdminBillingLedgerRoute =
  AppProtectedAdminBillingLedgerRouteImport.update({
    id: '/billing/ledger',
    path: '/billing/ledger',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminBillingStripeToolsRoute =
  AppProtectedAdminBillingStripeToolsRouteImport.update({
    id: '/billing/stripe-tools',
    path: '/billing/stripe-tools',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminBillingStuckStatesRoute =
  AppProtectedAdminBillingStuckStatesRouteImport.update({
    id: '/billing/stuck-states',
    path: '/billing/stuck-states',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminOrgsIndexRoute =
  AppProtectedAdminOrgsIndexRouteImport.update({
    id: '/orgs/',
    path: '/orgs/',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminOrgsOrgIdRoute =
  AppProtectedAdminOrgsOrgIdRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminProjectsIndexRoute =
  AppProtectedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminProjectsProjectIdRoute =
  AppProtectedAdminProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminUsersIndexRoute =
  AppProtectedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedAdminUsersUserIdRoute =
  AppProtectedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProtectedSettingsAccountIntegrationsRoute =
  AppProtectedSettingsAccountIntegrationsRouteImport.update({
    id: '/account/integrations',
    path: '/account/integrations',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const AppProtectedSettingsAccountPreferencesRoute =
  AppProtectedSettingsAccountPreferencesRouteImport.update({
    id: '/account/preferences',
    path: '/account/preferences',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const AppProtectedSettingsAccountProfileRoute =
  AppProtectedSettingsAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const AppProtectedSettingsAccountSecurityRoute =
  AppProtectedSettingsAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute =
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteImport.update({
    id: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs',
    path: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute =
  AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport.update(
    {
      id: '/studies/$studyId/checklists/$checklistId',
      path: '/studies/$studyId/checklists/$checklistId',
      getParentRoute: () => AppProtectedWorkspaceProjectsProjectIdRoute,
    } as any,
  )
const ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute =
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRouteImport.update({
    id: '/$fileName',
    path: '/$fileName',
    getParentRoute: () => ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute,
  } as any)
const AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute =
  AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport.update(
    {
      id: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id',
      path: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id',
      getParentRoute: () => AppProtectedWorkspaceProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/checklist': typeof AppChecklistRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/api/client-logs': typeof ApiClientLogsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/resources/amstar2': typeof ResourcesAmstar2Route
  '/resources/amstar2-vs-robis': typeof ResourcesAmstar2VsRobisRoute
  '/resources/rob1-vs-rob2': typeof ResourcesRob1VsRob2Route
  '/resources/rob2': typeof ResourcesRob2Route
  '/resources/rob2-vs-robins-i': typeof ResourcesRob2VsRobinsIRoute
  '/resources/robins-i': typeof ResourcesRobinsIRoute
  '/resources/robins-i-v1-vs-v2': typeof ResourcesRobinsIV1VsV2Route
  '/security/disclosure': typeof SecurityDisclosureRoute
  '/resources/': typeof ResourcesIndexRoute
  '/$workspace': typeof AppProtectedWorkspaceRouteWithChildren
  '/admin': typeof AppProtectedAdminRouteWithChildren
  '/settings': typeof AppProtectedSettingsRouteWithChildren
  '/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/test/add-project-member': typeof ApiTestAddProjectMemberRoute
  '/api/test/auth-code': typeof ApiTestAuthCodeRoute
  '/api/test/auth-url': typeof ApiTestAuthUrlRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/cleanup-user-by-email': typeof ApiTestCleanupUserByEmailRoute
  '/api/test/health': typeof ApiTestHealthRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/api/test/session': typeof ApiTestSessionRoute
  '/api/test/update-subscription': typeof ApiTestUpdateSubscriptionRoute
  '/api/test/verify-email': typeof ApiTestVerifyEmailRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/checklist/': typeof AppChecklistIndexRoute
  '/$workspace/settings': typeof AppProtectedWorkspaceSettingsRouteWithChildren
  '/admin/announcements': typeof AppProtectedAdminAnnouncementsRoute
  '/admin/database': typeof AppProtectedAdminDatabaseRoute
  '/admin/storage': typeof AppProtectedAdminStorageRoute
  '/orgs/new': typeof AppProtectedOrgsNewRoute
  '/projects/$': typeof AppProtectedProjectsSplatRoute
  '/settings/$': typeof AppProtectedSettingsSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/api/users/avatar/$userId': typeof ApiUsersAvatarUserIdRoute
  '/$workspace/': typeof AppProtectedWorkspaceIndexRoute
  '/admin/': typeof AppProtectedAdminIndexRoute
  '/settings/': typeof AppProtectedSettingsIndexRoute
  '/$workspace/projects/$projectId': typeof AppProtectedWorkspaceProjectsProjectIdRouteWithChildren
  '/$workspace/settings/billing': typeof AppProtectedWorkspaceSettingsBillingRoute
  '/$workspace/settings/plans': typeof AppProtectedWorkspaceSettingsPlansRoute
  '/admin/billing/ledger': typeof AppProtectedAdminBillingLedgerRoute
  '/admin/billing/stripe-tools': typeof AppProtectedAdminBillingStripeToolsRoute
  '/admin/billing/stuck-states': typeof AppProtectedAdminBillingStuckStatesRoute
  '/admin/orgs/$orgId': typeof AppProtectedAdminOrgsOrgIdRoute
  '/admin/projects/$projectId': typeof AppProtectedAdminProjectsProjectIdRoute
  '/admin/users/$userId': typeof AppProtectedAdminUsersUserIdRoute
  '/settings/account/integrations': typeof AppProtectedSettingsAccountIntegrationsRoute
  '/settings/account/preferences': typeof AppProtectedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof AppProtectedSettingsAccountProfileRoute
  '/settings/account/security': typeof AppProtectedSettingsAccountSecurityRoute
  '/$workspace/settings/': typeof AppProtectedWorkspaceSettingsIndexRoute
  '/admin/orgs/': typeof AppProtectedAdminOrgsIndexRoute
  '/admin/projects/': typeof AppProtectedAdminProjectsIndexRoute
  '/admin/users/': typeof AppProtectedAdminUsersIndexRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren
  '/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute
  '/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AppDashboardRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/api/client-logs': typeof ApiClientLogsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/resources/amstar2': typeof ResourcesAmstar2Route
  '/resources/amstar2-vs-robis': typeof ResourcesAmstar2VsRobisRoute
  '/resources/rob1-vs-rob2': typeof ResourcesRob1VsRob2Route
  '/resources/rob2': typeof ResourcesRob2Route
  '/resources/rob2-vs-robins-i': typeof ResourcesRob2VsRobinsIRoute
  '/resources/robins-i': typeof ResourcesRobinsIRoute
  '/resources/robins-i-v1-vs-v2': typeof ResourcesRobinsIV1VsV2Route
  '/security/disclosure': typeof SecurityDisclosureRoute
  '/resources': typeof ResourcesIndexRoute
  '/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/test/add-project-member': typeof ApiTestAddProjectMemberRoute
  '/api/test/auth-code': typeof ApiTestAuthCodeRoute
  '/api/test/auth-url': typeof ApiTestAuthUrlRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/cleanup-user-by-email': typeof ApiTestCleanupUserByEmailRoute
  '/api/test/health': typeof ApiTestHealthRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/api/test/session': typeof ApiTestSessionRoute
  '/api/test/update-subscription': typeof ApiTestUpdateSubscriptionRoute
  '/api/test/verify-email': typeof ApiTestVerifyEmailRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/checklist': typeof AppChecklistIndexRoute
  '/admin/announcements': typeof AppProtectedAdminAnnouncementsRoute
  '/admin/database': typeof AppProtectedAdminDatabaseRoute
  '/admin/storage': typeof AppProtectedAdminStorageRoute
  '/orgs/new': typeof AppProtectedOrgsNewRoute
  '/projects/$': typeof AppProtectedProjectsSplatRoute
  '/settings/$': typeof AppProtectedSettingsSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/api/users/avatar/$userId': typeof ApiUsersAvatarUserIdRoute
  '/$workspace': typeof AppProtectedWorkspaceIndexRoute
  '/admin': typeof AppProtectedAdminIndexRoute
  '/settings': typeof AppProtectedSettingsIndexRoute
  '/$workspace/projects/$projectId': typeof AppProtectedWorkspaceProjectsProjectIdRouteWithChildren
  '/$workspace/settings/billing': typeof AppProtectedWorkspaceSettingsBillingRoute
  '/$workspace/settings/plans': typeof AppProtectedWorkspaceSettingsPlansRoute
  '/admin/billing/ledger': typeof AppProtectedAdminBillingLedgerRoute
  '/admin/billing/stripe-tools': typeof AppProtectedAdminBillingStripeToolsRoute
  '/admin/billing/stuck-states': typeof AppProtectedAdminBillingStuckStatesRoute
  '/admin/orgs/$orgId': typeof AppProtectedAdminOrgsOrgIdRoute
  '/admin/projects/$projectId': typeof AppProtectedAdminProjectsProjectIdRoute
  '/admin/users/$userId': typeof AppProtectedAdminUsersUserIdRoute
  '/settings/account/integrations': typeof AppProtectedSettingsAccountIntegrationsRoute
  '/settings/account/preferences': typeof AppProtectedSettingsAccountPreferencesRoute
  '/settings/account/profile': typeof AppProtectedSettingsAccountProfileRoute
  '/settings/account/security': typeof AppProtectedSettingsAccountSecurityRoute
  '/$workspace/settings': typeof AppProtectedWorkspaceSettingsIndexRoute
  '/admin/orgs': typeof AppProtectedAdminOrgsIndexRoute
  '/admin/projects': typeof AppProtectedAdminProjectsIndexRoute
  '/admin/users': typeof AppProtectedAdminUsersIndexRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren
  '/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute
  '/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/healthz': typeof HealthzRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/_protected': typeof AppProtectedRouteWithChildren
  '/_app/checklist': typeof AppChecklistRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/api/client-logs': typeof ApiClientLogsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/resources/amstar2': typeof ResourcesAmstar2Route
  '/resources/amstar2-vs-robis': typeof ResourcesAmstar2VsRobisRoute
  '/resources/rob1-vs-rob2': typeof ResourcesRob1VsRob2Route
  '/resources/rob2': typeof ResourcesRob2Route
  '/resources/rob2-vs-robins-i': typeof ResourcesRob2VsRobinsIRoute
  '/resources/robins-i': typeof ResourcesRobinsIRoute
  '/resources/robins-i-v1-vs-v2': typeof ResourcesRobinsIV1VsV2Route
  '/security_/disclosure': typeof SecurityDisclosureRoute
  '/resources/': typeof ResourcesIndexRoute
  '/_app/_protected/$workspace': typeof AppProtectedWorkspaceRouteWithChildren
  '/_app/_protected/admin': typeof AppProtectedAdminRouteWithChildren
  '/_app/_protected/settings': typeof AppProtectedSettingsRouteWithChildren
  '/_app/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify-email': typeof ApiAuthVerifyEmailRoute
  '/api/test/add-project-member': typeof ApiTestAddProjectMemberRoute
  '/api/test/auth-code': typeof ApiTestAuthCodeRoute
  '/api/test/auth-url': typeof ApiTestAuthUrlRoute
  '/api/test/cleanup': typeof ApiTestCleanupRoute
  '/api/test/cleanup-user-by-email': typeof ApiTestCleanupUserByEmailRoute
  '/api/test/health': typeof ApiTestHealthRoute
  '/api/test/reset': typeof ApiTestResetRoute
  '/api/test/seed': typeof ApiTestSeedRoute
  '/api/test/session': typeof ApiTestSessionRoute
  '/api/test/update-subscription': typeof ApiTestUpdateSubscriptionRoute
  '/api/test/verify-email': typeof ApiTestVerifyEmailRoute
  '/api/users/avatar': typeof ApiUsersAvatarRouteWithChildren
  '/_app/checklist/': typeof AppChecklistIndexRoute
  '/_app/_protected/$workspace/settings': typeof AppProtectedWorkspaceSettingsRouteWithChildren
  '/_app/_protected/admin/announcements': typeof AppProtectedAdminAnnouncementsRoute
  '/_app/_protected/admin/database': typeof AppProtectedAdminDatabaseRoute
  '/_app/_protected/admin/storage': typeof AppProtectedAdminStorageRoute
  '/_app/_protected/orgs/new': typeof AppProtectedOrgsNewRoute
  '/_app/_protected/projects/$': typeof AppProtectedProjectsSplatRoute
  '/_app/_protected/settings/$': typeof AppProtectedSettingsSplatRoute
  '/api/auth/stripe/webhook': typeof ApiAuthStripeWebhookRoute
  '/api/users/avatar/$userId': typeof ApiUsersAvatarUserIdRoute
  '/_app/_protected/$workspace/': typeof AppProtectedWorkspaceIndexRoute
  '/_app/_protected/admin/': typeof AppProtectedAdminIndexRoute
  '/_app/_protected/settings/': typeof AppProtectedSettingsIndexRoute
  '/_app/_protected/$workspace/projects/$projectId': typeof AppProtectedWorkspaceProjectsProjectIdRouteWithChildren
  '/_app/_protected/$workspace/settings/billing': typeof AppProtectedWorkspaceSettingsBillingRoute
  '/_app/_protected/$workspace/settings/plans': typeof AppProtectedWorkspaceSettingsPlansRoute
  '/_app/_protected/admin/billing/ledger': typeof AppProtectedAdminBillingLedgerRoute
  '/_app/_protected/admin/billing/stripe-tools': typeof AppProtectedAdminBillingStripeToolsRoute
  '/_app/_protected/admin/billing/stuck-states': typeof AppProtectedAdminBillingStuckStatesRoute
  '/_app/_protected/admin/orgs/$orgId': typeof AppProtectedAdminOrgsOrgIdRoute
  '/_app/_protected/admin/projects/$projectId': typeof AppProtectedAdminProjectsProjectIdRoute
  '/_app/_protected/admin/users/$userId': typeof AppProtectedAdminUsersUserIdRoute
  '/_app/_protected/settings/account/integrations': typeof AppProtectedSettingsAccountIntegrationsRoute
  '/_app/_protected/settings/account/preferences': typeof AppProtectedSettingsAccountPreferencesRoute
  '/_app/_protected/settings/account/profile': typeof AppProtectedSettingsAccountProfileRoute
  '/_app/_protected/settings/account/security': typeof AppProtectedSettingsAccountSecurityRoute
  '/_app/_protected/$workspace/settings/': typeof AppProtectedWorkspaceSettingsIndexRoute
  '/_app/_protected/admin/orgs/': typeof AppProtectedAdminOrgsIndexRoute
  '/_app/_protected/admin/projects/': typeof AppProtectedAdminProjectsIndexRoute
  '/_app/_protected/admin/users/': typeof AppProtectedAdminUsersIndexRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren
  '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName': typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute
  '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/healthz'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/checklist'
    | '/dashboard'
    | '/complete-profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/api/client-logs'
    | '/invite/$token'
    | '/resources/amstar2'
    | '/resources/amstar2-vs-robis'
    | '/resources/rob1-vs-rob2'
    | '/resources/rob2'
    | '/resources/rob2-vs-robins-i'
    | '/resources/robins-i'
    | '/resources/robins-i-v1-vs-v2'
    | '/security/disclosure'
    | '/resources/'
    | '/$workspace'
    | '/admin'
    | '/settings'
    | '/checklist/$checklistId'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/test/add-project-member'
    | '/api/test/auth-code'
    | '/api/test/auth-url'
    | '/api/test/cleanup'
    | '/api/test/cleanup-user-by-email'
    | '/api/test/health'
    | '/api/test/reset'
    | '/api/test/seed'
    | '/api/test/session'
    | '/api/test/update-subscription'
    | '/api/test/verify-email'
    | '/api/users/avatar'
    | '/checklist/'
    | '/$workspace/settings'
    | '/admin/announcements'
    | '/admin/database'
    | '/admin/storage'
    | '/orgs/new'
    | '/projects/$'
    | '/settings/$'
    | '/api/auth/stripe/webhook'
    | '/api/users/avatar/$userId'
    | '/$workspace/'
    | '/admin/'
    | '/settings/'
    | '/$workspace/projects/$projectId'
    | '/$workspace/settings/billing'
    | '/$workspace/settings/plans'
    | '/admin/billing/ledger'
    | '/admin/billing/stripe-tools'
    | '/admin/billing/stuck-states'
    | '/admin/orgs/$orgId'
    | '/admin/projects/$projectId'
    | '/admin/users/$userId'
    | '/settings/account/integrations'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/$workspace/settings/'
    | '/admin/orgs/'
    | '/admin/projects/'
    | '/admin/users/'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
    | '/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
    | '/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/health'
    | '/healthz'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard'
    | '/complete-profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/api/client-logs'
    | '/invite/$token'
    | '/resources/amstar2'
    | '/resources/amstar2-vs-robis'
    | '/resources/rob1-vs-rob2'
    | '/resources/rob2'
    | '/resources/rob2-vs-robins-i'
    | '/resources/robins-i'
    | '/resources/robins-i-v1-vs-v2'
    | '/security/disclosure'
    | '/resources'
    | '/checklist/$checklistId'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/test/add-project-member'
    | '/api/test/auth-code'
    | '/api/test/auth-url'
    | '/api/test/cleanup'
    | '/api/test/cleanup-user-by-email'
    | '/api/test/health'
    | '/api/test/reset'
    | '/api/test/seed'
    | '/api/test/session'
    | '/api/test/update-subscription'
    | '/api/test/verify-email'
    | '/api/users/avatar'
    | '/checklist'
    | '/admin/announcements'
    | '/admin/database'
    | '/admin/storage'
    | '/orgs/new'
    | '/projects/$'
    | '/settings/$'
    | '/api/auth/stripe/webhook'
    | '/api/users/avatar/$userId'
    | '/$workspace'
    | '/admin'
    | '/settings'
    | '/$workspace/projects/$projectId'
    | '/$workspace/settings/billing'
    | '/$workspace/settings/plans'
    | '/admin/billing/ledger'
    | '/admin/billing/stripe-tools'
    | '/admin/billing/stuck-states'
    | '/admin/orgs/$orgId'
    | '/admin/projects/$projectId'
    | '/admin/users/$userId'
    | '/settings/account/integrations'
    | '/settings/account/preferences'
    | '/settings/account/profile'
    | '/settings/account/security'
    | '/$workspace/settings'
    | '/admin/orgs'
    | '/admin/projects'
    | '/admin/users'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
    | '/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
    | '/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/about'
    | '/contact'
    | '/health'
    | '/healthz'
    | '/pricing'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/_protected'
    | '/_app/checklist'
    | '/_app/dashboard'
    | '/_auth/complete-profile'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/api/$'
    | '/api/client-logs'
    | '/invite/$token'
    | '/resources/amstar2'
    | '/resources/amstar2-vs-robis'
    | '/resources/rob1-vs-rob2'
    | '/resources/rob2'
    | '/resources/rob2-vs-robins-i'
    | '/resources/robins-i'
    | '/resources/robins-i-v1-vs-v2'
    | '/security_/disclosure'
    | '/resources/'
    | '/_app/_protected/$workspace'
    | '/_app/_protected/admin'
    | '/_app/_protected/settings'
    | '/_app/checklist/$checklistId'
    | '/api/auth/$'
    | '/api/auth/session'
    | '/api/auth/verify-email'
    | '/api/test/add-project-member'
    | '/api/test/auth-code'
    | '/api/test/auth-url'
    | '/api/test/cleanup'
    | '/api/test/cleanup-user-by-email'
    | '/api/test/health'
    | '/api/test/reset'
    | '/api/test/seed'
    | '/api/test/session'
    | '/api/test/update-subscription'
    | '/api/test/verify-email'
    | '/api/users/avatar'
    | '/_app/checklist/'
    | '/_app/_protected/$workspace/settings'
    | '/_app/_protected/admin/announcements'
    | '/_app/_protected/admin/database'
    | '/_app/_protected/admin/storage'
    | '/_app/_protected/orgs/new'
    | '/_app/_protected/projects/$'
    | '/_app/_protected/settings/$'
    | '/api/auth/stripe/webhook'
    | '/api/users/avatar/$userId'
    | '/_app/_protected/$workspace/'
    | '/_app/_protected/admin/'
    | '/_app/_protected/settings/'
    | '/_app/_protected/$workspace/projects/$projectId'
    | '/_app/_protected/$workspace/settings/billing'
    | '/_app/_protected/$workspace/settings/plans'
    | '/_app/_protected/admin/billing/ledger'
    | '/_app/_protected/admin/billing/stripe-tools'
    | '/_app/_protected/admin/billing/stuck-states'
    | '/_app/_protected/admin/orgs/$orgId'
    | '/_app/_protected/admin/projects/$projectId'
    | '/_app/_protected/admin/users/$userId'
    | '/_app/_protected/settings/account/integrations'
    | '/_app/_protected/settings/account/preferences'
    | '/_app/_protected/settings/account/profile'
    | '/_app/_protected/settings/account/security'
    | '/_app/_protected/$workspace/settings/'
    | '/_app/_protected/admin/orgs/'
    | '/_app/_protected/admin/projects/'
    | '/_app/_protected/admin/users/'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
    | '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
    | '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HealthRoute: typeof HealthRoute
  HealthzRoute: typeof HealthzRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiClientLogsRoute: typeof ApiClientLogsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ResourcesAmstar2Route: typeof ResourcesAmstar2Route
  ResourcesAmstar2VsRobisRoute: typeof ResourcesAmstar2VsRobisRoute
  ResourcesRob1VsRob2Route: typeof ResourcesRob1VsRob2Route
  ResourcesRob2Route: typeof ResourcesRob2Route
  ResourcesRob2VsRobinsIRoute: typeof ResourcesRob2VsRobinsIRoute
  ResourcesRobinsIRoute: typeof ResourcesRobinsIRoute
  ResourcesRobinsIV1VsV2Route: typeof ResourcesRobinsIV1VsV2Route
  SecurityDisclosureRoute: typeof SecurityDisclosureRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyEmailRoute: typeof ApiAuthVerifyEmailRoute
  ApiTestAddProjectMemberRoute: typeof ApiTestAddProjectMemberRoute
  ApiTestAuthCodeRoute: typeof ApiTestAuthCodeRoute
  ApiTestAuthUrlRoute: typeof ApiTestAuthUrlRoute
  ApiTestCleanupRoute: typeof ApiTestCleanupRoute
  ApiTestCleanupUserByEmailRoute: typeof ApiTestCleanupUserByEmailRoute
  ApiTestHealthRoute: typeof ApiTestHealthRoute
  ApiTestResetRoute: typeof ApiTestResetRoute
  ApiTestSeedRoute: typeof ApiTestSeedRoute
  ApiTestSessionRoute: typeof ApiTestSessionRoute
  ApiTestUpdateSubscriptionRoute: typeof ApiTestUpdateSubscriptionRoute
  ApiTestVerifyEmailRoute: typeof ApiTestVerifyEmailRoute
  ApiUsersAvatarRoute: typeof ApiUsersAvatarRouteWithChildren
  ApiAuthStripeWebhookRoute: typeof ApiAuthStripeWebhookRoute
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute: typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklist': {
      id: '/_app/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-logs': {
      id: '/api/client-logs'
      path: '/api/client-logs'
      fullPath: '/api/client-logs'
      preLoaderRoute: typeof ApiClientLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/amstar2': {
      id: '/resources/amstar2'
      path: '/resources/amstar2'
      fullPath: '/resources/amstar2'
      preLoaderRoute: typeof ResourcesAmstar2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/amstar2-vs-robis': {
      id: '/resources/amstar2-vs-robis'
      path: '/resources/amstar2-vs-robis'
      fullPath: '/resources/amstar2-vs-robis'
      preLoaderRoute: typeof ResourcesAmstar2VsRobisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/rob1-vs-rob2': {
      id: '/resources/rob1-vs-rob2'
      path: '/resources/rob1-vs-rob2'
      fullPath: '/resources/rob1-vs-rob2'
      preLoaderRoute: typeof ResourcesRob1VsRob2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/rob2': {
      id: '/resources/rob2'
      path: '/resources/rob2'
      fullPath: '/resources/rob2'
      preLoaderRoute: typeof ResourcesRob2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/rob2-vs-robins-i': {
      id: '/resources/rob2-vs-robins-i'
      path: '/resources/rob2-vs-robins-i'
      fullPath: '/resources/rob2-vs-robins-i'
      preLoaderRoute: typeof ResourcesRob2VsRobinsIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/robins-i': {
      id: '/resources/robins-i'
      path: '/resources/robins-i'
      fullPath: '/resources/robins-i'
      preLoaderRoute: typeof ResourcesRobinsIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/robins-i-v1-vs-v2': {
      id: '/resources/robins-i-v1-vs-v2'
      path: '/resources/robins-i-v1-vs-v2'
      fullPath: '/resources/robins-i-v1-vs-v2'
      preLoaderRoute: typeof ResourcesRobinsIV1VsV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security_/disclosure': {
      id: '/security_/disclosure'
      path: '/security/disclosure'
      fullPath: '/security/disclosure'
      preLoaderRoute: typeof SecurityDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected/$workspace': {
      id: '/_app/_protected/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof AppProtectedWorkspaceRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/admin': {
      id: '/_app/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppProtectedAdminRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/settings': {
      id: '/_app/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppProtectedSettingsRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/checklist/': {
      id: '/_app/checklist/'
      path: '/'
      fullPath: '/checklist/'
      preLoaderRoute: typeof AppChecklistIndexRouteImport
      parentRoute: typeof AppChecklistRoute
    }
    '/_app/checklist/$checklistId': {
      id: '/_app/checklist/$checklistId'
      path: '/$checklistId'
      fullPath: '/checklist/$checklistId'
      preLoaderRoute: typeof AppChecklistChecklistIdRouteImport
      parentRoute: typeof AppChecklistRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify-email': {
      id: '/api/auth/verify-email'
      path: '/api/auth/verify-email'
      fullPath: '/api/auth/verify-email'
      preLoaderRoute: typeof ApiAuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/add-project-member': {
      id: '/api/test/add-project-member'
      path: '/api/test/add-project-member'
      fullPath: '/api/test/add-project-member'
      preLoaderRoute: typeof ApiTestAddProjectMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/auth-code': {
      id: '/api/test/auth-code'
      path: '/api/test/auth-code'
      fullPath: '/api/test/auth-code'
      preLoaderRoute: typeof ApiTestAuthCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/auth-url': {
      id: '/api/test/auth-url'
      path: '/api/test/auth-url'
      fullPath: '/api/test/auth-url'
      preLoaderRoute: typeof ApiTestAuthUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/cleanup': {
      id: '/api/test/cleanup'
      path: '/api/test/cleanup'
      fullPath: '/api/test/cleanup'
      preLoaderRoute: typeof ApiTestCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/cleanup-user-by-email': {
      id: '/api/test/cleanup-user-by-email'
      path: '/api/test/cleanup-user-by-email'
      fullPath: '/api/test/cleanup-user-by-email'
      preLoaderRoute: typeof ApiTestCleanupUserByEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/health': {
      id: '/api/test/health'
      path: '/api/test/health'
      fullPath: '/api/test/health'
      preLoaderRoute: typeof ApiTestHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/reset': {
      id: '/api/test/reset'
      path: '/api/test/reset'
      fullPath: '/api/test/reset'
      preLoaderRoute: typeof ApiTestResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/seed': {
      id: '/api/test/seed'
      path: '/api/test/seed'
      fullPath: '/api/test/seed'
      preLoaderRoute: typeof ApiTestSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/session': {
      id: '/api/test/session'
      path: '/api/test/session'
      fullPath: '/api/test/session'
      preLoaderRoute: typeof ApiTestSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/update-subscription': {
      id: '/api/test/update-subscription'
      path: '/api/test/update-subscription'
      fullPath: '/api/test/update-subscription'
      preLoaderRoute: typeof ApiTestUpdateSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/verify-email': {
      id: '/api/test/verify-email'
      path: '/api/test/verify-email'
      fullPath: '/api/test/verify-email'
      preLoaderRoute: typeof ApiTestVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/avatar': {
      id: '/api/users/avatar'
      path: '/api/users/avatar'
      fullPath: '/api/users/avatar'
      preLoaderRoute: typeof ApiUsersAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected/$workspace/': {
      id: '/_app/_protected/$workspace/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof AppProtectedWorkspaceIndexRouteImport
      parentRoute: typeof AppProtectedWorkspaceRoute
    }
    '/_app/_protected/$workspace/settings': {
      id: '/_app/_protected/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof AppProtectedWorkspaceSettingsRouteImport
      parentRoute: typeof AppProtectedWorkspaceRoute
    }
    '/_app/_protected/admin/': {
      id: '/_app/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppProtectedAdminIndexRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/announcements': {
      id: '/_app/_protected/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AppProtectedAdminAnnouncementsRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/database': {
      id: '/_app/_protected/admin/database'
      path: '/database'
      fullPath: '/admin/database'
      preLoaderRoute: typeof AppProtectedAdminDatabaseRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/storage': {
      id: '/_app/_protected/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AppProtectedAdminStorageRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/orgs/new': {
      id: '/_app/_protected/orgs/new'
      path: '/orgs/new'
      fullPath: '/orgs/new'
      preLoaderRoute: typeof AppProtectedOrgsNewRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/projects/$': {
      id: '/_app/_protected/projects/$'
      path: '/projects/$'
      fullPath: '/projects/$'
      preLoaderRoute: typeof AppProtectedProjectsSplatRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/settings/': {
      id: '/_app/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppProtectedSettingsIndexRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/_app/_protected/settings/$': {
      id: '/_app/_protected/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof AppProtectedSettingsSplatRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/api/auth/stripe/webhook': {
      id: '/api/auth/stripe/webhook'
      path: '/api/auth/stripe/webhook'
      fullPath: '/api/auth/stripe/webhook'
      preLoaderRoute: typeof ApiAuthStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/avatar/$userId': {
      id: '/api/users/avatar/$userId'
      path: '/$userId'
      fullPath: '/api/users/avatar/$userId'
      preLoaderRoute: typeof ApiUsersAvatarUserIdRouteImport
      parentRoute: typeof ApiUsersAvatarRoute
    }
    '/_app/_protected/$workspace/projects/$projectId': {
      id: '/_app/_protected/$workspace/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$workspace/projects/$projectId'
      preLoaderRoute: typeof AppProtectedWorkspaceProjectsProjectIdRouteImport
      parentRoute: typeof AppProtectedWorkspaceRoute
    }
    '/_app/_protected/$workspace/settings/': {
      id: '/_app/_protected/$workspace/settings/'
      path: '/'
      fullPath: '/$workspace/settings/'
      preLoaderRoute: typeof AppProtectedWorkspaceSettingsIndexRouteImport
      parentRoute: typeof AppProtectedWorkspaceSettingsRoute
    }
    '/_app/_protected/$workspace/settings/billing': {
      id: '/_app/_protected/$workspace/settings/billing'
      path: '/billing'
      fullPath: '/$workspace/settings/billing'
      preLoaderRoute: typeof AppProtectedWorkspaceSettingsBillingRouteImport
      parentRoute: typeof AppProtectedWorkspaceSettingsRoute
    }
    '/_app/_protected/$workspace/settings/plans': {
      id: '/_app/_protected/$workspace/settings/plans'
      path: '/plans'
      fullPath: '/$workspace/settings/plans'
      preLoaderRoute: typeof AppProtectedWorkspaceSettingsPlansRouteImport
      parentRoute: typeof AppProtectedWorkspaceSettingsRoute
    }
    '/_app/_protected/admin/billing/ledger': {
      id: '/_app/_protected/admin/billing/ledger'
      path: '/billing/ledger'
      fullPath: '/admin/billing/ledger'
      preLoaderRoute: typeof AppProtectedAdminBillingLedgerRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/billing/stripe-tools': {
      id: '/_app/_protected/admin/billing/stripe-tools'
      path: '/billing/stripe-tools'
      fullPath: '/admin/billing/stripe-tools'
      preLoaderRoute: typeof AppProtectedAdminBillingStripeToolsRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/billing/stuck-states': {
      id: '/_app/_protected/admin/billing/stuck-states'
      path: '/billing/stuck-states'
      fullPath: '/admin/billing/stuck-states'
      preLoaderRoute: typeof AppProtectedAdminBillingStuckStatesRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/orgs/': {
      id: '/_app/_protected/admin/orgs/'
      path: '/orgs'
      fullPath: '/admin/orgs/'
      preLoaderRoute: typeof AppProtectedAdminOrgsIndexRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/orgs/$orgId': {
      id: '/_app/_protected/admin/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof AppProtectedAdminOrgsOrgIdRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/projects/': {
      id: '/_app/_protected/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AppProtectedAdminProjectsIndexRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/projects/$projectId': {
      id: '/_app/_protected/admin/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AppProtectedAdminProjectsProjectIdRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/users/': {
      id: '/_app/_protected/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppProtectedAdminUsersIndexRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/admin/users/$userId': {
      id: '/_app/_protected/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AppProtectedAdminUsersUserIdRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/_protected/settings/account/integrations': {
      id: '/_app/_protected/settings/account/integrations'
      path: '/account/integrations'
      fullPath: '/settings/account/integrations'
      preLoaderRoute: typeof AppProtectedSettingsAccountIntegrationsRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/_app/_protected/settings/account/preferences': {
      id: '/_app/_protected/settings/account/preferences'
      path: '/account/preferences'
      fullPath: '/settings/account/preferences'
      preLoaderRoute: typeof AppProtectedSettingsAccountPreferencesRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/_app/_protected/settings/account/profile': {
      id: '/_app/_protected/settings/account/profile'
      path: '/account/profile'
      fullPath: '/settings/account/profile'
      preLoaderRoute: typeof AppProtectedSettingsAccountProfileRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/_app/_protected/settings/account/security': {
      id: '/_app/_protected/settings/account/security'
      path: '/account/security'
      fullPath: '/settings/account/security'
      preLoaderRoute: typeof AppProtectedSettingsAccountSecurityRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs': {
      id: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
      path: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
      fullPath: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs'
      preLoaderRoute: typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId': {
      id: '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId'
      path: '/studies/$studyId/checklists/$checklistId'
      fullPath: '/$workspace/projects/$projectId/studies/$studyId/checklists/$checklistId'
      preLoaderRoute: typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport
      parentRoute: typeof AppProtectedWorkspaceProjectsProjectIdRoute
    }
    '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName': {
      id: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
      path: '/$fileName'
      fullPath: '/api/orgs/$orgId/projects/$projectId/studies/$studyId/pdfs/$fileName'
      preLoaderRoute: typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRouteImport
      parentRoute: typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute
    }
    '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': {
      id: '/_app/_protected/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      path: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      fullPath: '/$workspace/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      preLoaderRoute: typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport
      parentRoute: typeof AppProtectedWorkspaceProjectsProjectIdRoute
    }
  }
}

interface AppProtectedWorkspaceSettingsRouteChildren {
  AppProtectedWorkspaceSettingsBillingRoute: typeof AppProtectedWorkspaceSettingsBillingRoute
  AppProtectedWorkspaceSettingsPlansRoute: typeof AppProtectedWorkspaceSettingsPlansRoute
  AppProtectedWorkspaceSettingsIndexRoute: typeof AppProtectedWorkspaceSettingsIndexRoute
}

const AppProtectedWorkspaceSettingsRouteChildren: AppProtectedWorkspaceSettingsRouteChildren =
  {
    AppProtectedWorkspaceSettingsBillingRoute:
      AppProtectedWorkspaceSettingsBillingRoute,
    AppProtectedWorkspaceSettingsPlansRoute:
      AppProtectedWorkspaceSettingsPlansRoute,
    AppProtectedWorkspaceSettingsIndexRoute:
      AppProtectedWorkspaceSettingsIndexRoute,
  }

const AppProtectedWorkspaceSettingsRouteWithChildren =
  AppProtectedWorkspaceSettingsRoute._addFileChildren(
    AppProtectedWorkspaceSettingsRouteChildren,
  )

interface AppProtectedWorkspaceProjectsProjectIdRouteChildren {
  AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute: typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute: typeof AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}

const AppProtectedWorkspaceProjectsProjectIdRouteChildren: AppProtectedWorkspaceProjectsProjectIdRouteChildren =
  {
    AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute:
      AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute,
    AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute:
      AppProtectedWorkspaceProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute,
  }

const AppProtectedWorkspaceProjectsProjectIdRouteWithChildren =
  AppProtectedWorkspaceProjectsProjectIdRoute._addFileChildren(
    AppProtectedWorkspaceProjectsProjectIdRouteChildren,
  )

interface AppProtectedWorkspaceRouteChildren {
  AppProtectedWorkspaceSettingsRoute: typeof AppProtectedWorkspaceSettingsRouteWithChildren
  AppProtectedWorkspaceIndexRoute: typeof AppProtectedWorkspaceIndexRoute
  AppProtectedWorkspaceProjectsProjectIdRoute: typeof AppProtectedWorkspaceProjectsProjectIdRouteWithChildren
}

const AppProtectedWorkspaceRouteChildren: AppProtectedWorkspaceRouteChildren = {
  AppProtectedWorkspaceSettingsRoute:
    AppProtectedWorkspaceSettingsRouteWithChildren,
  AppProtectedWorkspaceIndexRoute: AppProtectedWorkspaceIndexRoute,
  AppProtectedWorkspaceProjectsProjectIdRoute:
    AppProtectedWorkspaceProjectsProjectIdRouteWithChildren,
}

const AppProtectedWorkspaceRouteWithChildren =
  AppProtectedWorkspaceRoute._addFileChildren(
    AppProtectedWorkspaceRouteChildren,
  )

interface AppProtectedAdminRouteChildren {
  AppProtectedAdminAnnouncementsRoute: typeof AppProtectedAdminAnnouncementsRoute
  AppProtectedAdminDatabaseRoute: typeof AppProtectedAdminDatabaseRoute
  AppProtectedAdminStorageRoute: typeof AppProtectedAdminStorageRoute
  AppProtectedAdminIndexRoute: typeof AppProtectedAdminIndexRoute
  AppProtectedAdminBillingLedgerRoute: typeof AppProtectedAdminBillingLedgerRoute
  AppProtectedAdminBillingStripeToolsRoute: typeof AppProtectedAdminBillingStripeToolsRoute
  AppProtectedAdminBillingStuckStatesRoute: typeof AppProtectedAdminBillingStuckStatesRoute
  AppProtectedAdminOrgsOrgIdRoute: typeof AppProtectedAdminOrgsOrgIdRoute
  AppProtectedAdminProjectsProjectIdRoute: typeof AppProtectedAdminProjectsProjectIdRoute
  AppProtectedAdminUsersUserIdRoute: typeof AppProtectedAdminUsersUserIdRoute
  AppProtectedAdminOrgsIndexRoute: typeof AppProtectedAdminOrgsIndexRoute
  AppProtectedAdminProjectsIndexRoute: typeof AppProtectedAdminProjectsIndexRoute
  AppProtectedAdminUsersIndexRoute: typeof AppProtectedAdminUsersIndexRoute
}

const AppProtectedAdminRouteChildren: AppProtectedAdminRouteChildren = {
  AppProtectedAdminAnnouncementsRoute: AppProtectedAdminAnnouncementsRoute,
  AppProtectedAdminDatabaseRoute: AppProtectedAdminDatabaseRoute,
  AppProtectedAdminStorageRoute: AppProtectedAdminStorageRoute,
  AppProtectedAdminIndexRoute: AppProtectedAdminIndexRoute,
  AppProtectedAdminBillingLedgerRoute: AppProtectedAdminBillingLedgerRoute,
  AppProtectedAdminBillingStripeToolsRoute:
    AppProtectedAdminBillingStripeToolsRoute,
  AppProtectedAdminBillingStuckStatesRoute:
    AppProtectedAdminBillingStuckStatesRoute,
  AppProtectedAdminOrgsOrgIdRoute: AppProtectedAdminOrgsOrgIdRoute,
  AppProtectedAdminProjectsProjectIdRoute:
    AppProtectedAdminProjectsProjectIdRoute,
  AppProtectedAdminUsersUserIdRoute: AppProtectedAdminUsersUserIdRoute,
  AppProtectedAdminOrgsIndexRoute: AppProtectedAdminOrgsIndexRoute,
  AppProtectedAdminProjectsIndexRoute: AppProtectedAdminProjectsIndexRoute,
  AppProtectedAdminUsersIndexRoute: AppProtectedAdminUsersIndexRoute,
}

const AppProtectedAdminRouteWithChildren =
  AppProtectedAdminRoute._addFileChildren(AppProtectedAdminRouteChildren)

interface AppProtectedSettingsRouteChildren {
  AppProtectedSettingsSplatRoute: typeof AppProtectedSettingsSplatRoute
  AppProtectedSettingsIndexRoute: typeof AppProtectedSettingsIndexRoute
  AppProtectedSettingsAccountIntegrationsRoute: typeof AppProtectedSettingsAccountIntegrationsRoute
  AppProtectedSettingsAccountPreferencesRoute: typeof AppProtectedSettingsAccountPreferencesRoute
  AppProtectedSettingsAccountProfileRoute: typeof AppProtectedSettingsAccountProfileRoute
  AppProtectedSettingsAccountSecurityRoute: typeof AppProtectedSettingsAccountSecurityRoute
}

const AppProtectedSettingsRouteChildren: AppProtectedSettingsRouteChildren = {
  AppProtectedSettingsSplatRoute: AppProtectedSettingsSplatRoute,
  AppProtectedSettingsIndexRoute: AppProtectedSettingsIndexRoute,
  AppProtectedSettingsAccountIntegrationsRoute:
    AppProtectedSettingsAccountIntegrationsRoute,
  AppProtectedSettingsAccountPreferencesRoute:
    AppProtectedSettingsAccountPreferencesRoute,
  AppProtectedSettingsAccountProfileRoute:
    AppProtectedSettingsAccountProfileRoute,
  AppProtectedSettingsAccountSecurityRoute:
    AppProtectedSettingsAccountSecurityRoute,
}

const AppProtectedSettingsRouteWithChildren =
  AppProtectedSettingsRoute._addFileChildren(AppProtectedSettingsRouteChildren)

interface AppProtectedRouteChildren {
  AppProtectedWorkspaceRoute: typeof AppProtectedWorkspaceRouteWithChildren
  AppProtectedAdminRoute: typeof AppProtectedAdminRouteWithChildren
  AppProtectedSettingsRoute: typeof AppProtectedSettingsRouteWithChildren
  AppProtectedOrgsNewRoute: typeof AppProtectedOrgsNewRoute
  AppProtectedProjectsSplatRoute: typeof AppProtectedProjectsSplatRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedWorkspaceRoute: AppProtectedWorkspaceRouteWithChildren,
  AppProtectedAdminRoute: AppProtectedAdminRouteWithChildren,
  AppProtectedSettingsRoute: AppProtectedSettingsRouteWithChildren,
  AppProtectedOrgsNewRoute: AppProtectedOrgsNewRoute,
  AppProtectedProjectsSplatRoute: AppProtectedProjectsSplatRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

interface AppChecklistRouteChildren {
  AppChecklistChecklistIdRoute: typeof AppChecklistChecklistIdRoute
  AppChecklistIndexRoute: typeof AppChecklistIndexRoute
}

const AppChecklistRouteChildren: AppChecklistRouteChildren = {
  AppChecklistChecklistIdRoute: AppChecklistChecklistIdRoute,
  AppChecklistIndexRoute: AppChecklistIndexRoute,
}

const AppChecklistRouteWithChildren = AppChecklistRoute._addFileChildren(
  AppChecklistRouteChildren,
)

interface AppRouteChildren {
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
  AppChecklistRoute: typeof AppChecklistRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProtectedRoute: AppProtectedRouteWithChildren,
  AppChecklistRoute: AppChecklistRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiUsersAvatarRouteChildren {
  ApiUsersAvatarUserIdRoute: typeof ApiUsersAvatarUserIdRoute
}

const ApiUsersAvatarRouteChildren: ApiUsersAvatarRouteChildren = {
  ApiUsersAvatarUserIdRoute: ApiUsersAvatarUserIdRoute,
}

const ApiUsersAvatarRouteWithChildren = ApiUsersAvatarRoute._addFileChildren(
  ApiUsersAvatarRouteChildren,
)

interface ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteChildren {
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute: typeof ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute
}

const ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteChildren: ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteChildren =
  {
    ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute:
      ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsFileNameRoute,
  }

const ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren =
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute._addFileChildren(
    ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HealthRoute: HealthRoute,
  HealthzRoute: HealthzRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiClientLogsRoute: ApiClientLogsRoute,
  InviteTokenRoute: InviteTokenRoute,
  ResourcesAmstar2Route: ResourcesAmstar2Route,
  ResourcesAmstar2VsRobisRoute: ResourcesAmstar2VsRobisRoute,
  ResourcesRob1VsRob2Route: ResourcesRob1VsRob2Route,
  ResourcesRob2Route: ResourcesRob2Route,
  ResourcesRob2VsRobinsIRoute: ResourcesRob2VsRobinsIRoute,
  ResourcesRobinsIRoute: ResourcesRobinsIRoute,
  ResourcesRobinsIV1VsV2Route: ResourcesRobinsIV1VsV2Route,
  SecurityDisclosureRoute: SecurityDisclosureRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyEmailRoute: ApiAuthVerifyEmailRoute,
  ApiTestAddProjectMemberRoute: ApiTestAddProjectMemberRoute,
  ApiTestAuthCodeRoute: ApiTestAuthCodeRoute,
  ApiTestAuthUrlRoute: ApiTestAuthUrlRoute,
  ApiTestCleanupRoute: ApiTestCleanupRoute,
  ApiTestCleanupUserByEmailRoute: ApiTestCleanupUserByEmailRoute,
  ApiTestHealthRoute: ApiTestHealthRoute,
  ApiTestResetRoute: ApiTestResetRoute,
  ApiTestSeedRoute: ApiTestSeedRoute,
  ApiTestSessionRoute: ApiTestSessionRoute,
  ApiTestUpdateSubscriptionRoute: ApiTestUpdateSubscriptionRoute,
  ApiTestVerifyEmailRoute: ApiTestVerifyEmailRoute,
  ApiUsersAvatarRoute: ApiUsersAvatarRouteWithChildren,
  ApiAuthStripeWebhookRoute: ApiAuthStripeWebhookRoute,
  ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRoute:
    ApiOrgsOrgIdProjectsProjectIdStudiesStudyIdPdfsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
