/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthCompleteProfileRouteImport } from './routes/_auth.complete-profile'
import { Route as AuthCheckEmailRouteImport } from './routes/_auth.check-email'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChecklistRouteImport } from './routes/_app.checklist'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppChecklistChecklistIdRouteImport } from './routes/_app.checklist.$checklistId'
import { Route as AppProtectedSettingsRouteImport } from './routes/_app._protected.settings'
import { Route as AppProtectedProfileRouteImport } from './routes/_app._protected.profile'
import { Route as AppProtectedAdminRouteImport } from './routes/_app._protected.admin'
import { Route as AppProtectedSettingsBillingRouteImport } from './routes/_app._protected.settings.billing'
import { Route as AppProtectedAdminStorageRouteImport } from './routes/_app._protected.admin.storage'
import { Route as AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport } from './routes/_app.projects.$projectId.studies.$studyId.checklists.$checklistId'
import { Route as AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport } from './routes/_app.projects.$projectId.studies.$studyId.reconcile.$checklist1Id.$checklist2Id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCompleteProfileRoute = AuthCompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckEmailRoute = AuthCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistRoute = AppChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AppRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppChecklistChecklistIdRoute = AppChecklistChecklistIdRouteImport.update({
  id: '/$checklistId',
  path: '/$checklistId',
  getParentRoute: () => AppChecklistRoute,
} as any)
const AppProtectedSettingsRoute = AppProtectedSettingsRouteImport.update({
  id: '/_protected/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/_protected/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedAdminRoute = AppProtectedAdminRouteImport.update({
  id: '/_protected/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedSettingsBillingRoute =
  AppProtectedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AppProtectedSettingsRoute,
  } as any)
const AppProtectedAdminStorageRoute =
  AppProtectedAdminStorageRouteImport.update({
    id: '/storage',
    path: '/storage',
    getParentRoute: () => AppProtectedAdminRoute,
  } as any)
const AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute =
  AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport.update({
    id: '/studies/$studyId/checklists/$checklistId',
    path: '/studies/$studyId/checklists/$checklistId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any)
const AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute =
  AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport.update(
    {
      id: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id',
      path: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id',
      getParentRoute: () => AppProjectsProjectIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/checklist': typeof AppChecklistRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AppProtectedAdminRouteWithChildren
  '/profile': typeof AppProtectedProfileRoute
  '/settings': typeof AppProtectedSettingsRouteWithChildren
  '/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/storage': typeof AppProtectedAdminStorageRoute
  '/settings/billing': typeof AppProtectedSettingsBillingRoute
  '/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/checklist': typeof AppChecklistRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/check-email': typeof AuthCheckEmailRoute
  '/complete-profile': typeof AuthCompleteProfileRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AppProtectedAdminRouteWithChildren
  '/profile': typeof AppProtectedProfileRoute
  '/settings': typeof AppProtectedSettingsRouteWithChildren
  '/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/admin/storage': typeof AppProtectedAdminStorageRoute
  '/settings/billing': typeof AppProtectedSettingsBillingRoute
  '/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/_app/checklist': typeof AppChecklistRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_auth/check-email': typeof AuthCheckEmailRoute
  '/_auth/complete-profile': typeof AuthCompleteProfileRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_app/_protected/admin': typeof AppProtectedAdminRouteWithChildren
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_app/_protected/settings': typeof AppProtectedSettingsRouteWithChildren
  '/_app/checklist/$checklistId': typeof AppChecklistChecklistIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_app/_protected/admin/storage': typeof AppProtectedAdminStorageRoute
  '/_app/_protected/settings/billing': typeof AppProtectedSettingsBillingRoute
  '/_app/projects/$projectId/studies/$studyId/checklists/$checklistId': typeof AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  '/_app/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': typeof AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/terms'
    | '/checklist'
    | '/dashboard'
    | '/check-email'
    | '/complete-profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/demo/tanstack-query'
    | '/admin'
    | '/profile'
    | '/settings'
    | '/checklist/$checklistId'
    | '/projects/$projectId'
    | '/demo/start/server-funcs'
    | '/admin/storage'
    | '/settings/billing'
    | '/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/terms'
    | '/checklist'
    | '/dashboard'
    | '/check-email'
    | '/complete-profile'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/demo/tanstack-query'
    | '/admin'
    | '/profile'
    | '/settings'
    | '/checklist/$checklistId'
    | '/projects/$projectId'
    | '/demo/start/server-funcs'
    | '/admin/storage'
    | '/settings/billing'
    | '/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_app'
    | '/_auth'
    | '/_protected'
    | '/about'
    | '/contact'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/security'
    | '/terms'
    | '/_app/checklist'
    | '/_app/dashboard'
    | '/_auth/check-email'
    | '/_auth/complete-profile'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/demo/tanstack-query'
    | '/_app/_protected/admin'
    | '/_app/_protected/profile'
    | '/_app/_protected/settings'
    | '/_app/checklist/$checklistId'
    | '/_app/projects/$projectId'
    | '/demo/start/server-funcs'
    | '/_app/_protected/admin/storage'
    | '/_app/_protected/settings/billing'
    | '/_app/projects/$projectId/studies/$studyId/checklists/$checklistId'
    | '/_app/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/complete-profile': {
      id: '/_auth/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof AuthCompleteProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/check-email': {
      id: '/_auth/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof AuthCheckEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklist': {
      id: '/_app/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AppChecklistRouteImport
      parentRoute: typeof AppRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checklist/$checklistId': {
      id: '/_app/checklist/$checklistId'
      path: '/$checklistId'
      fullPath: '/checklist/$checklistId'
      preLoaderRoute: typeof AppChecklistChecklistIdRouteImport
      parentRoute: typeof AppChecklistRoute
    }
    '/_app/_protected/settings': {
      id: '/_app/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppProtectedSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/admin': {
      id: '/_app/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppProtectedAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/settings/billing': {
      id: '/_app/_protected/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppProtectedSettingsBillingRouteImport
      parentRoute: typeof AppProtectedSettingsRoute
    }
    '/_app/_protected/admin/storage': {
      id: '/_app/_protected/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AppProtectedAdminStorageRouteImport
      parentRoute: typeof AppProtectedAdminRoute
    }
    '/_app/projects/$projectId/studies/$studyId/checklists/$checklistId': {
      id: '/_app/projects/$projectId/studies/$studyId/checklists/$checklistId'
      path: '/studies/$studyId/checklists/$checklistId'
      fullPath: '/projects/$projectId/studies/$studyId/checklists/$checklistId'
      preLoaderRoute: typeof AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id': {
      id: '/_app/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      path: '/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      fullPath: '/projects/$projectId/studies/$studyId/reconcile/$checklist1Id/$checklist2Id'
      preLoaderRoute: typeof AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
  }
}

interface AppChecklistRouteChildren {
  AppChecklistChecklistIdRoute: typeof AppChecklistChecklistIdRoute
}

const AppChecklistRouteChildren: AppChecklistRouteChildren = {
  AppChecklistChecklistIdRoute: AppChecklistChecklistIdRoute,
}

const AppChecklistRouteWithChildren = AppChecklistRoute._addFileChildren(
  AppChecklistRouteChildren,
)

interface AppProtectedAdminRouteChildren {
  AppProtectedAdminStorageRoute: typeof AppProtectedAdminStorageRoute
}

const AppProtectedAdminRouteChildren: AppProtectedAdminRouteChildren = {
  AppProtectedAdminStorageRoute: AppProtectedAdminStorageRoute,
}

const AppProtectedAdminRouteWithChildren =
  AppProtectedAdminRoute._addFileChildren(AppProtectedAdminRouteChildren)

interface AppProtectedSettingsRouteChildren {
  AppProtectedSettingsBillingRoute: typeof AppProtectedSettingsBillingRoute
}

const AppProtectedSettingsRouteChildren: AppProtectedSettingsRouteChildren = {
  AppProtectedSettingsBillingRoute: AppProtectedSettingsBillingRoute,
}

const AppProtectedSettingsRouteWithChildren =
  AppProtectedSettingsRoute._addFileChildren(AppProtectedSettingsRouteChildren)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute: typeof AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute
  AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute: typeof AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute:
    AppProjectsProjectIdStudiesStudyIdChecklistsChecklistIdRoute,
  AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute:
    AppProjectsProjectIdStudiesStudyIdReconcileChecklist1IdChecklist2IdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppChecklistRoute: typeof AppChecklistRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppProtectedAdminRoute: typeof AppProtectedAdminRouteWithChildren
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
  AppProtectedSettingsRoute: typeof AppProtectedSettingsRouteWithChildren
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppChecklistRoute: AppChecklistRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppProtectedAdminRoute: AppProtectedAdminRouteWithChildren,
  AppProtectedProfileRoute: AppProtectedProfileRoute,
  AppProtectedSettingsRoute: AppProtectedSettingsRouteWithChildren,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCheckEmailRoute: typeof AuthCheckEmailRoute
  AuthCompleteProfileRoute: typeof AuthCompleteProfileRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCheckEmailRoute: AuthCheckEmailRoute,
  AuthCompleteProfileRoute: AuthCompleteProfileRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
